### ISSUE TITLE
Bundle fails with dist/excalibur.d.ts is not a module.

### ISSUE THREAD

**Issue by tetious** [excaliburjs/example-ts-webpack#1]
When I run webpack, I get the following error:

```
ERROR in ./index.ts
(1,21): error TS2306: File '/[...]/node_modules/excalibur/dist/excalibur.d.ts' is not a module.
```

I found a workaround that requires manually editing the definition file, adding: `export = ex;` which seems less than ideal. Is this expected?

**Comment by kamranayub** [comment]
Make sure you're using latest edge of Excalibur. 0.8 doesn't have module
support yet. Let us know if that helps!

**Comment by tetious** [comment]
I imagine that would work fine, however I think given this repo is meant to be a clone and go sorta deal for folks new to excalibur, either this caveat (or description of the export = ex workaround, which might be easier) should be in the readme, or the package.json should point to a compatible version. 

As far as I can tell, the edge version isn't on npm, and the version referenced is "broken." This makes it more difficult for newbies to get up and running quickly. :)

**Comment by kamranayub** [comment]
Yes, agreed, I think the npm tag is "next" but our docs have the Unstable
Builds steps documented. I just haven't gotten around to fixing the
reference, as this was the first example repo I put together... The rest of
them reference the right package.

**Comment by kamranayub** [comment]
Just updated it, thanks for pointing it out!

**Comment by tetious** [comment]
Yeah, I was digging into this further as I didn't know you could tag npm releases, and found the one you referenced in the other projects and was gonna do a PR. :)

Thanks! It's working just fine now. :)
